# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kitap_duzenle.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(585, 659)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(60, 460, 471, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 30, 401, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sil_button = QtWidgets.QPushButton(self.layoutWidget)
        self.sil_button.setObjectName("sil_button")
        self.gridLayout_2.addWidget(self.sil_button, 0, 3, 1, 1)
        self.ekle_button = QtWidgets.QPushButton(self.layoutWidget)
        self.ekle_button.setObjectName("ekle_button")
        self.gridLayout_2.addWidget(self.ekle_button, 0, 0, 1, 1)
        self.guncelle_button = QtWidgets.QPushButton(self.layoutWidget)
        self.guncelle_button.setObjectName("guncelle_button")
        self.gridLayout_2.addWidget(self.guncelle_button, 0, 2, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(110, 20, 371, 411))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.id_label = QtWidgets.QLabel(self.frame)
        self.id_label.setObjectName("id_label")
        self.gridLayout.addWidget(self.id_label, 0, 0, 1, 1)
        self.id_line_edit = QtWidgets.QLineEdit(self.frame)
        self.id_line_edit.setObjectName("id_line_edit")
        self.gridLayout.addWidget(self.id_line_edit, 0, 1, 1, 3)
        self.kitap_adi_label = QtWidgets.QLabel(self.frame)
        self.kitap_adi_label.setObjectName("kitap_adi_label")
        self.gridLayout.addWidget(self.kitap_adi_label, 1, 0, 1, 2)
        self.kitap_adi_line_edit = QtWidgets.QLineEdit(self.frame)
        self.kitap_adi_line_edit.setObjectName("kitap_adi_line_edit")
        self.gridLayout.addWidget(self.kitap_adi_line_edit, 1, 3, 1, 1)
        self.Yazar_adi_label = QtWidgets.QLabel(self.frame)
        self.Yazar_adi_label.setObjectName("Yazar_adi_label")
        self.gridLayout.addWidget(self.Yazar_adi_label, 2, 0, 1, 2)
        self.yazar_adi_line_edit = QtWidgets.QLineEdit(self.frame)
        self.yazar_adi_line_edit.setObjectName("yazar_adi_line_edit")
        self.gridLayout.addWidget(self.yazar_adi_line_edit, 2, 2, 1, 2)
        self.sayfa_sayisi_label = QtWidgets.QLabel(self.frame)
        self.sayfa_sayisi_label.setObjectName("sayfa_sayisi_label")
        self.gridLayout.addWidget(self.sayfa_sayisi_label, 3, 0, 1, 1)
        self.sayfa_sayisi_line_edit = QtWidgets.QLineEdit(self.frame)
        self.sayfa_sayisi_line_edit.setObjectName("sayfa_sayisi_line_edit")
        self.gridLayout.addWidget(self.sayfa_sayisi_line_edit, 3, 2, 1, 2)
        self.kategori_label = QtWidgets.QLabel(self.frame)
        self.kategori_label.setObjectName("kategori_label")
        self.gridLayout.addWidget(self.kategori_label, 4, 0, 1, 2)
        self.kategori_line_edit = QtWidgets.QLineEdit(self.frame)
        self.kategori_line_edit.setObjectName("kategori_line_edit")
        self.gridLayout.addWidget(self.kategori_line_edit, 4, 2, 1, 2)
        self.fiyat_label = QtWidgets.QLabel(self.frame)
        self.fiyat_label.setObjectName("fiyat_label")
        self.gridLayout.addWidget(self.fiyat_label, 5, 0, 1, 1)
        self.fiyat_line_Edit = QtWidgets.QLineEdit(self.frame)
        self.fiyat_line_Edit.setObjectName("fiyat_line_Edit")
        self.gridLayout.addWidget(self.fiyat_line_Edit, 5, 3, 1, 1)
        self.eklendigi_tarih = QtWidgets.QLabel(self.frame)
        self.eklendigi_tarih.setObjectName("eklendigi_tarih")
        self.gridLayout.addWidget(self.eklendigi_tarih, 6, 0, 1, 3)
        self.eklendigi_tarih_line_edit = QtWidgets.QLineEdit(self.frame)
        self.eklendigi_tarih_line_edit.setObjectName("eklendigi_tarih_line_edit")
        self.gridLayout.addWidget(self.eklendigi_tarih_line_edit, 6, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sil_button.setText(_translate("Form", "Sil"))
        self.ekle_button.setText(_translate("Form", "Ekle"))
        self.guncelle_button.setText(_translate("Form", "Güncelle"))
        self.id_label.setText(_translate("Form", "<html><head/><body><p align=\"center\">ID</p></body></html>"))
        self.kitap_adi_label.setText(_translate("Form", "Kitap Adı"))
        self.Yazar_adi_label.setText(_translate("Form", "Yazar Adı"))
        self.sayfa_sayisi_label.setText(_translate("Form", "Sayfa Sayısı"))
        self.kategori_label.setText(_translate("Form", "Kategori"))
        self.fiyat_label.setText(_translate("Form", "Fiyat"))
        self.eklendigi_tarih.setText(_translate("Form", "Eklendiği Tarih"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
