# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kitap_bilgi_sayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(995, 502)
        self.arama_yap_line_edit = QtWidgets.QLineEdit(Form)
        self.arama_yap_line_edit.setGeometry(QtCore.QRect(100, 130, 741, 20))
        self.arama_yap_line_edit.setObjectName("arama_yap_line_edit")
        self.bilgi_tableWidget = QtWidgets.QTableWidget(Form)
        self.bilgi_tableWidget.setGeometry(QtCore.QRect(40, 180, 891, 281))
        self.bilgi_tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bilgi_tableWidget.setShowGrid(False)
        self.bilgi_tableWidget.setObjectName("bilgi_tableWidget")
        self.bilgi_tableWidget.setColumnCount(5)
        self.bilgi_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(4, item)
        self.bilgi_tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.bilgi_tableWidget.horizontalHeader().setStretchLastSection(True)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Kitap Adı"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Satın Alan Kişi"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Adres"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Yapılan Ödeme"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
